knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration

        # the key "facebook_main" can be anything, it
        # will create a service: "knpu.oauth2.client.facebook_main"
        facebook_main:
            # this will be one of the supported types
            type: facebook
#            client_id: '%env(OAUTH_FACEBOOK_ID)%'
#            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%
            client_id: '1215193168634355'
            client_secret: 'e69f0c375814fa4b288440a687fa9c50'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v2.12